title: Ziang Xiao
url: "https://www.ziangxiao.com"
baseurl: "/"

markdown: kramdown

tracking_id: UA-120527594-1

footer: yes
footer_url: "https://ziangxiao.github.io"
footer_text: "Last Updated Jan 2020"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/"
 - name: "Curriculum Vitae"
   link: "ziangxiaoCV.pdf"
 - name: "Contact"
   link: "contact"
