title: Ziang Xiao
url: "https://www.ziangxiao.com"
baseurl: "/"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: UA-120527594-1

footer: yes
footer_url: "https://ziangxiao.github.io"
footer_text: "Last Updated Dec 2019"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/"
 - name: "Curriculum Vitae (updated Dec 19)"
   link: "ziangxiaoCV.pdf"
 - name: "Contact"
   link: "contact"
